version: '3.7'
services:
  trino:
    image: 'trinodb/trino:390'
    hostname: trino
    ports:
      - '8085:8080'
    volumes:
      - ./etc:/etc/trino
      - ./conf:/etc/trino/conf
    networks:
      - trino-network

  postgres:
    image: 'postgres:11'
    hostname: postgres
    # expose:
    #   - '5432'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: source_db
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d source_db -U admin"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - trino-network

  hive-metastore:
    image: 'my-hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres
        # condition: service_healthy
    networks:
      - trino-network

  last_postgres:
    image: postgres:11
    # expose:
    #   - "5434"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - trino-network

  elt:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt.py"]
    networks:
      - trino-network
    depends_on:
      - postgres
      - last_postgres

  minio:
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    hostname: minio
    container_name: minio
    ports:
      - '9095:9000'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
    networks:
      - trino-network

volumes:
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge
